[project]
name = "land-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "remy000", email = "dukundaneremy2001@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "numpy>=2.5.3",
    "onnxruntime>=1.30.0",
    "pillow>=12.3.0",
    "pydantic-settings>=2.15.0",
]

[dependency-groups]
ml = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "onnx>=1.23.1",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

